### ISSUE TITLE
Генератор чисел выдает только одно число

### ISSUE THREAD

**Issue by Spectrum735** [deluvsushi/RandStuffAPI#1]
Генератор не работает, как надо. Даже если явно указать количество чисел и диапазон, он всё равно выдает одно число из диапазона от 1 до 100. Как заставить выдать 12 чисел?

**Comment by vraestoren** [comment]
Обновил библиотеку проблема решена.
```python3
import randstuff
randstuff = randstuff.RandStuff()
numbers = randstuff.generate_random_number(count=12)["number"]
print(numbers)
```
